# Generated by Django 2.1.1 on 2018-09-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180915_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonent',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='abonent',
            name='telega_id',
            field=models.IntegerField(verbose_name='ID'),
        ),
    ]
