# Generated by Django 2.1.1 on 2018-09-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180915_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonent',
            options={'ordering': ['telega_id']},
        ),
        migrations.AddField(
            model_name='abonent',
            name='job_seeker',
            field=models.BooleanField(default=False, verbose_name='Ищет работу'),
        ),
        migrations.AddField(
            model_name='abonent',
            name='support_seeker',
            field=models.BooleanField(default=False, verbose_name='Ждет связи с оператором'),
        ),
        migrations.AlterField(
            model_name='abonent',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='名称为啥'),
        ),
    ]
