# Generated by Django 2.1.1 on 2018-09-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180915_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonent',
            name='payment_instance',
            field=models.IntegerField(default=0, verbose_name='инстанс платёжки'),
        ),
    ]
