# Generated by Django 2.1.1 on 2018-09-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_type_of_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена, если пусто, то ценник берется с вида продукции'),
        ),
        migrations.AddField(
            model_name='product_type',
            name='price',
            field=models.FloatField(default=500, verbose_name='Цена за ед. продукта, по дефолту с неё берется ценник на товары'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
