# Generated by Django 2.1.1 on 2018-09-17 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='finished_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnId', models.CharField(blank=True, max_length=128, verbose_name='Номер транзакции')),
                ('total_amount', models.FloatField(blank=True, verbose_name='Сумма')),
                ('abonent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.abonent', verbose_name='Пополнитель(из телеги)')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.abonent', verbose_name='Покупатель'),
        ),
    ]
