# Generated by Django 2.1.1 on 2018-09-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180918_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finished_transaction',
            old_name='total_amount',
            new_name='cash',
        ),
    ]
