# Generated by Django 2.1.1 on 2018-09-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180918_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commentary',
            field=models.TextField(null=True, verbose_name='Дополнительное описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='foto_link',
            field=models.URLField(max_length=256, null=True, verbose_name='ссылка на фото'),
        ),
    ]
