# Generated by Django 2.1.1 on 2018-10-01 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180921_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата продажи'),
        ),
    ]
