# Generated by Django 2.1.1 on 2018-10-12 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20181001_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_date']},
        ),
        migrations.AddField(
            model_name='abonent',
            name='fake_purchases',
            field=models.ManyToManyField(blank=True, related_name='fake_one', to='core.product', verbose_name='Список транзакциий апп'),
        ),
        migrations.AddField(
            model_name='product',
            name='geolocation',
            field=models.URLField(max_length=256, null=True, verbose_name='Ссылка на геолокацию'),
        ),
        migrations.AddField(
            model_name='site_settings',
            name='qiwi_token',
            field=models.CharField(blank=True, max_length=128, verbose_name='токен киви'),
        ),
        migrations.AddField(
            model_name='site_settings',
            name='qiwi_wallet_num',
            field=models.CharField(blank=True, max_length=128, verbose_name='номер киви'),
        ),
        migrations.AddField(
            model_name='site_settings',
            name='tele_token',
            field=models.CharField(blank=True, max_length=128, verbose_name='токен телеги'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='foto_link',
            field=models.URLField(max_length=256, null=True, verbose_name='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата продажи'),
        ),
        migrations.AlterField(
            model_name='site_settings',
            name='product_main_spec',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название первой категории'),
        ),
        migrations.AlterField(
            model_name='site_settings',
            name='shop_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название магазина'),
        ),
    ]
