# Generated by Django 2.1.1 on 2018-12-15 12:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20181012_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='telegram_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_type', models.CharField(choices=[('bai', 'белая'), ('hei', 'черная'), ('hui', 'серая')], default='hei', max_length=22, verbose_name='Тип кассы')),
                ('tg_token', models.CharField(max_length=128, verbose_name='tg_token')),
                ('tg_id', models.CharField(max_length=128, verbose_name='tg_id')),
                ('tg_type', models.CharField(choices=[('tg_dv_fake', 'tg_dv_fake')], default='hei', max_length=22, verbose_name='Тип телеги')),
                ('web_hook_chained', models.BooleanField(default=False, verbose_name='вебхук')),
                ('start_word', models.CharField(max_length=128, verbose_name='стартовая фраза')),
            ],
            options={
                'ordering': ['tg_id'],
            },
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('amount', models.FloatField(default=0, verbose_name='amount')),
                ('paid_transaction', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('project_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.telegram_project', verbose_name='project_fk')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
