# Generated by Django 2.1.1 on 2018-12-16 06:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_telegram_project_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='project_fk',
        ),
        migrations.AlterModelOptions(
            name='chat_msg',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='finished_transaction',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='chat_msg',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='finished_transaction',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='finished_transaction',
            name='paid_transaction',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='finished_transaction',
            name='project_fk',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='core.telegram_project', verbose_name='project_fk'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finished_transaction',
            name='cash',
            field=models.FloatField(default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='telegram_project',
            name='tg_id',
            field=models.CharField(max_length=128, verbose_name='tg_id, 为了看清楚'),
        ),
        migrations.AlterField(
            model_name='telegram_project',
            name='tg_type',
            field=models.CharField(choices=[('tg_dv_fake', 'tg_dv_fake')], default='tg_dv_fake', max_length=22, verbose_name='Тип телеги'),
        ),
        migrations.DeleteModel(
            name='transaction',
        ),
    ]
