# Generated by Django 2.1.1 on 2018-12-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20181216_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram_project',
            name='tg_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='tg_name, 为了看清楚'),
        ),
        migrations.AlterField(
            model_name='telegram_project',
            name='tg_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='tg_id, 为了看清楚'),
        ),
    ]
