# Generated by Django 2.1.1 on 2018-12-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_telegram_project_finance_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegram_project',
            options={'ordering': ['tg_username']},
        ),
        migrations.RemoveField(
            model_name='telegram_project',
            name='tg_name',
        ),
        migrations.AddField(
            model_name='telegram_project',
            name='tg_first_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='tg_first_name, 为了看清楚'),
        ),
        migrations.AddField(
            model_name='telegram_project',
            name='tg_username',
            field=models.CharField(blank=True, max_length=128, verbose_name='tg_username, 为了看清楚'),
        ),
    ]
