# Generated by Django 2.1.1 on 2018-12-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20181216_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram_project',
            name='tg_type',
            field=models.CharField(choices=[('tg_shop_fake', 'tg_shop_fake')], default='tg_shop_fake', max_length=22, verbose_name='Тип телеги'),
        ),
    ]
