# Generated by Django 2.1.1 on 2018-12-17 16:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20181216_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='bought_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='tuple s dannimi o pokupke')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('abonent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.abonent', verbose_name='Пополнитель(из телеги)')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
