# Generated by Django 2.1.1 on 2018-12-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20181222_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raion',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='raion',
            name='longitude',
        ),
    ]
